name: Linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Install Requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot cdbs dh-make cmake build-essential

      - name: Build Packages
        run: ./build-packages.sh
