name: Linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Install GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          export DEB_SIGN_KEYID=6D001E7B8B0F585699DCEF658896C9EF9A7B7CA0

      - name: Install Requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot cdbs dh-make cmake build-essential

      - name: Build Packages
        run: ./build-packages.sh

      - name: Archive Package
        uses: actions/upload-artifact@v2
        with:
          name: github-packages_1.0.0_amd64
          path: build/*
